version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix(deps)"
    groups:
      nuget-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix(deps)"
    groups:
      docs-python:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix(deps)"
    groups:
      react-router:
        patterns:
          - "react-router"
          - "@react-router/*"
        update-types:
          - minor
          - patch
      npm-minor-and-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "react-router"
          - "@react-router/*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
