// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NzbWebDAV.Database;

#nullable disable

namespace NzbWebDAV.Database.PostgresMigrations
{
    [DbContext(typeof(PostgresDavDatabaseContext))]
    partial class PostgresDavDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NzbWebDAV.Database.Models.Account", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RandomSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Type", "Username");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_SingleAdmin")
                        .HasFilter("\"Type\" = 1");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ArticleMissCacheEntry", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasColumnType("text");

                    b.Property<long>("ConfirmedAtUnix")
                        .HasColumnType("bigint");

                    b.HasKey("CacheKey");

                    b.HasIndex("ConfirmedAtUnix");

                    b.ToTable("ArticleMissCacheEntries", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.BlobCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BlobCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ConfigItem", b =>
                {
                    b.Property<string>("ConfigName")
                        .HasColumnType("text");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConfigName");

                    b.ToTable("ConfigItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DavCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArrDownloadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("FileBlobId")
                        .HasColumnType("uuid");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("GeneratedStrmOutputRoot")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedStrmPath")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedStrmTarget")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedSymlinkOutputRoot")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedSymlinkPath")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedSymlinkTarget")
                        .HasColumnType("text");

                    b.Property<bool>("HealthRepairPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("UrgentRepairFailures")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HistoryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("LastHealthCheck")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("NextHealthCheck")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("NzbBlobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ReleaseDate")
                        .HasColumnType("bigint");

                    b.Property<int>("SubType")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NzbBlobId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("HealthRepairPending", "NextHealthCheck");

                    b.HasIndex("IdPrefix", "Type");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.HasIndex("HistoryItemId", "SubType", "CreatedAt");

                    b.HasIndex("HistoryItemId", "Type", "CreatedAt");

                    b.HasIndex("Type", "HistoryItemId", "NextHealthCheck", "ReleaseDate", "Id");

                    b.ToTable("DavItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavMultipartFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavMultipartFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavNzbFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("SegmentIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavNzbFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavRarFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("RarParts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DavRarFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HealthCheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DavItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("NzbFileName")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepairStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DavItemId")
                        .HasFilter("\"RepairStatus\" = 3");

                    b.HasIndex("RepairStatus", "CreatedAt")
                        .HasFilter("\"RepairStatus\" IN (1, 2)");

                    b.HasIndex("Result", "RepairStatus", "CreatedAt");

                    b.ToTable("HealthCheckResults", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HealthCheckStat", b =>
                {
                    b.Property<long>("DateStartInclusive")
                        .HasColumnType("bigint");

                    b.Property<long>("DateEndExclusive")
                        .HasColumnType("bigint");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("RepairStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("DateStartInclusive", "DateEndExclusive", "Result", "RepairStatus");

                    b.ToTable("HealthCheckStats", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HistoryCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteMountedFiles")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("HistoryCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.HistoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArrDownloadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentGroupKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DownloadDirId")
                        .HasColumnType("uuid");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("integer");

                    b.Property<int>("DownloadTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FailMessage")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndexerName")
                        .HasColumnType("text");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("LastPlayedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("NzbBlobId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalSegmentBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NzbBlobId");

                    b.HasIndex("Category", "CreatedAt");

                    b.HasIndex("Category", "DownloadDirId");

                    b.HasIndex("ContentGroupKey", "DownloadStatus");

                    b.ToTable("HistoryItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.IndexerApiHit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccessedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("IndexerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessedAt");

                    b.HasIndex("IndexerName", "Type", "AccessedAt");

                    b.ToTable("IndexerApiHits", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.ListSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Cap")
                        .HasColumnType("integer");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text");

                    b.Property<long?>("LastSyncedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeriesScope")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ListSources", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NzbBlobCleanupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NzbBlobCleanupItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NzbName", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NzbNames", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.NzbResolutionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidatesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfileToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokensJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUnix");

                    b.ToTable("NzbResolutionGroups", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.Par2RepairJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<long>("BytesRead")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DavItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("MissingSegmentIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("NextAttemptAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SlicesReconstructed")
                        .HasColumnType("integer");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DavItemId");

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("Par2RepairJobs", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.LibraryLinkMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DavItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MappingType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkPath")
                        .IsUnique();

                    b.HasIndex("DavItemId");

                    b.ToTable("LibraryLinkMaps", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArrDownloadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentGroupKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndexerName")
                        .HasColumnType("text");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("NzbFileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PauseUntil")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PostProcessing")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<long>("SortOrder")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSegmentBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ContentGroupKey");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Priority");

                    b.HasIndex("Category", "FileName")
                        .IsUnique();

                    b.HasIndex("Priority", "SortOrder");

                    b.HasIndex("Category", "Priority", "SortOrder");

                    b.ToTable("QueueItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueNzbContents", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("NzbContents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QueueNzbContents", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.SetupWizardState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Disposition")
                        .HasColumnType("integer");

                    b.Property<string>("IngestionMethods")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("WizardVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SetupWizardStates", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.WantedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("FailReason")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("LastResolvedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastVerifiedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<long?>("NextCheckAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponderHost")
                        .HasColumnType("text");

                    b.Property<string>("Shortlist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("WinnerNzb")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("NextCheckAtUnix");

                    b.HasIndex("State");

                    b.HasIndex("UpdatedAtUnix");

                    b.ToTable("WantedItems", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.WatchdogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AttemptedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CandidateTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClickId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentGroupKey")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("FailReason")
                        .HasColumnType("text");

                    b.Property<string>("IndexerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderHost")
                        .HasColumnType("text");

                    b.Property<Guid?>("QueueItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("RankIndex")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("ContentGroupKey");

                    b.HasIndex("QueueItemId");

                    b.ToTable("WatchdogEntries", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavMultipartFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavMultipartFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavNzbFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavNzbFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.DavRarFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.DavItem", "DavItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.DavRarFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DavItem");
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.QueueNzbContents", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.QueueItem", "QueueItem")
                        .WithOne()
                        .HasForeignKey("NzbWebDAV.Database.Models.QueueNzbContents", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueItem");
                });
#pragma warning restore 612, 618
        }
    }
}
