import type { FileResourceRow, FilesResourcePage } from "~/clients/files-contract";
export function makeFileRow(overrides: Partial<FileResourceRow> = {}): FileResourceRow {
  return {
    key: "10000000-0000-0000-0000-000000000001",
    id: "10000000-0000-0000-0000-000000000001",
    parentId: "00000000-0000-0000-0000-000000000002",
    name: "Synthetic.mkv",
    path: "/content/Synthetic.mkv",
    isDirectory: false,
    hasChildren: false,
    size: 1024,
    subType: 201,
    addedAt: "2026-09-23T00:00:00+00:00",
    releaseDate: null,
    lastHealthCheck: null,
    nextCheckAt: null,
    health: "unknown",
    scanState: "queued",
    progress: null,
    healthResultId: null,
    healthResultAt: null,
    repairAction: null,
    healthMessage: null,
    historyItemId: null,
    jobName: null,
    nzbFileName: null,
    category: null,
    indexerName: null,
    lastPlayedAt: null,
    nzbBlobId: null,
    libraryState: "not-configured",
    libraryLinkCount: 0,
    libraryPaths: [],
    canRecheck: true,
    recheckDisabledReason: null,
    canDelete: true,
    deleteDisabledReason: null,
    canSearchArr: false,
    searchArrDisabledReason: "Configure Arr.",
    mimeType: "video/x-matroska",
    previewUrl: "/synthetic-media",
    ...overrides,
  };
}
export function makeFilesPage(
  rows: FileResourceRow[],
  overrides: Partial<FilesResourcePage> = {},
): FilesResourcePage {
  return {
    status: true,
    mode: "tree",
    scopePath: "/content",
    parentPath: "/content",
    offset: 0,
    limit: 100,
    totalRows: rows.length,
    matchingFileCount: rows.filter((row) => !row.isDirectory).length,
    hasMore: false,
    observedAt: "2026-09-23T12:00:00+00:00",
    libraryScanState: "not-configured",
    libraryScannedAt: null,
    libraryError: null,
    schedule: {
      timeZoneId: "UTC",
      checksOpen: true,
      repairsOpen: true,
      nextChecksChange: null,
      nextRepairsChange: null,
      pendingRepairCount: 0,
      manualRunActive: false,
    },
    rows,
    ...overrides,
  };
}
