// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzbWebDAV.Database;

#nullable disable

namespace NzbWebDAV.Database.UsenetMigrations
{
    [DbContext(typeof(UsenetMigrationDbContext))]
    [Migration("20260920111042_AddNzbDavCanarySource")]
    partial class AddNzbDavCanarySource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigratedFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleIdentityDigest")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleIdentityKind")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DavItemId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("MigratedReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalisedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NzbBlobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DavItemId");

                    b.HasIndex("NzbBlobId");

                    b.HasIndex("MigratedReleaseId", "SourceFileId");

                    b.HasIndex("MigratedReleaseId", "VirtualPath")
                        .IsUnique();

                    b.ToTable("MigratedFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigratedRelease", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MappedFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MigratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MountPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("NzoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCategory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastRunId");

                    b.HasIndex("NzoId");

                    b.HasIndex("SourceType", "SourceReleaseId")
                        .IsUnique();

                    b.ToTable("MigratedReleases", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationCanaryLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplyStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationEvidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewRelativeTarget")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLegacyTarget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePackageDigest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplyStatus");

                    b.HasIndex("CorrelationStatus");

                    b.HasIndex("RunId", "LibraryRelativePath")
                        .IsUnique();

                    b.ToTable("CanaryLinks", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationCategoryMap", b =>
                {
                    b.Property<string>("AltmountCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltmountDir")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltmountSanitizedDir")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltmountType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCategory")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AltmountCategory");

                    b.ToTable("CategoryMap", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationPreferences", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltmountConfigPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltmountMetadataRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltmountStoreRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanaryLibraryRoot")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQueueDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePackageRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("altmount");

                    b.Property<int>("SubmitWorkers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymlinkBackupDir")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymlinkLibraryRoot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MigrationPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_MigrationPreferences_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationRelease", b =>
                {
                    b.Property<string>("StoreRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltmountCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollisionGroupKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Encryption")
                        .HasColumnType("TEXT");

                    b.Property<long>("EstFetchBytesEager")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EstFetchBytesLazy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EstStatCommands")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasClipBoundaries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasFilenamePassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasNestedSources")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Included")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRarRelease")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("JobNameDiverges")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetaFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NzbFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceNzbdavId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreBasename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmitFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCategory")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerdictDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerdictReasons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorstFileStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("StoreRef");

                    b.HasIndex("CollisionGroupKey");

                    b.HasIndex("JobName");

                    b.HasIndex("TargetCategory");

                    b.HasIndex("TargetCategory", "QueueFileName");

                    b.HasIndex("Verdict", "Included");

                    b.ToTable("Releases", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationReleaseFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleIdentityDigest")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleIdentityKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flags")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewDavItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NzbdavId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalisedName");

                    b.HasIndex("StoreRef");

                    b.HasIndex("StoreRef", "SourceFileId");

                    b.ToTable("ReleaseFiles", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("MigrationRuns", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationScanError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanErrors", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationSessionState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltmountConfigPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltmountMetadataRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltmountStoreRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanaryLibraryRoot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrentRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQueueDepth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RunCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RunStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScanCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ScanLazyRarEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScanStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ScanWindowsSafePaths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePackageRoot")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("altmount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmitWorkers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymlinkBackupDir")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymlinkLibraryRoot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionState", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionState_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationSubmission", b =>
                {
                    b.Property<string>("StoreRef")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DavItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HistoryClearedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MountPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("NzoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("StoreRef");

                    b.HasIndex("State");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationSymlinkRewrite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewTarget")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldTarget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymlinkPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("SymlinkRewrites", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigratedFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.UsenetMigration.MigratedRelease", null)
                        .WithMany()
                        .HasForeignKey("MigratedReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationCanaryLink", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.UsenetMigration.MigrationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationReleaseFile", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.UsenetMigration.MigrationRelease", null)
                        .WithMany()
                        .HasForeignKey("StoreRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.UsenetMigration.MigrationSubmission", b =>
                {
                    b.HasOne("NzbWebDAV.Database.Models.UsenetMigration.MigrationRelease", null)
                        .WithMany()
                        .HasForeignKey("StoreRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
